import { getCollection } from 'astro:content';
import type { MindmapData } from './types.js';
import { MindmapParser } from './parser.js';

export class MindmapContentLoader {
  private parser: MindmapParser;
  private contentCache: Map<string, MindmapData> = new Map();

  constructor() {
    this.parser = new MindmapParser();
  }

  /**
   * Load mindmap content for a specific lesson
   */
  public async loadMindmapForLesson(course: string, lessonSlug: string): Promise<MindmapData | null> {
    const cacheKey = `${course}/${lessonSlug}`;
    
    // Check cache first
    if (this.contentCache.has(cacheKey)) {
      return this.contentCache.get(cacheKey)!;
    }

    try {
      // Try different mindmap file patterns
      const mindmapContent = await this.findMindmapContent(course, lessonSlug);
      
      if (mindmapContent) {
        const mindmapData = this.parser.parseContent(mindmapContent.content);
        
        // Update metadata with lesson info
        mindmapData.metadata = {
          ...mindmapData.metadata,
          course: mindmapContent.frontmatter.course || course,
          chapter: mindmapContent.frontmatter.chapter,
          lessonSlug
        };

        // Cache the result
        this.contentCache.set(cacheKey, mindmapData);
        return mindmapData;
      }

      // Fallback: Try to auto-generate from lesson content
      return await this.generateFromLessonContent(course, lessonSlug);

    } catch (error) {
      console.error(`Failed to load mindmap for ${course}/${lessonSlug}:`, error);
      return null;
    }
  }

  /**
   * Find dedicated mindmap content using various naming patterns
   */
  private async findMindmapContent(course: string, lessonSlug: string): Promise<{content: string, frontmatter: any} | null> {
    try {
      // Get all courses from the content collection
      const allCourses = await getCollection('courses');
      
      // Look for mindmap files using different patterns
      const mindmapPatterns = [
        `${lessonSlug}/5_Mindmap`, // Standard pattern: folder/5_Mindmap
        `${lessonSlug}-mindmap`, // Alternative: lessonSlug-mindmap
        `${lessonSlug}_mindmap`, // Alternative: lessonSlug_mindmap
        'mindmap', // Just "mindmap" in the same folder
        '5_Mindmap' // Standard mindmap file name
      ];

      for (const pattern of mindmapPatterns) {
        const mindmapFile = allCourses.find(lesson => {
          const courseName = lesson.data.course?.toLowerCase().replace(/\s+/g, '-');
          const lessonPath = lesson.slug.split('/').slice(1).join('/'); // Remove course prefix
          
          return courseName === course && (
            lessonPath === pattern ||
            lessonPath.endsWith(`/${pattern}`) ||
            lessonPath.includes(pattern)
          );
        });

        if (mindmapFile && mindmapFile.body.includes('- **')) {
          // Found a mindmap file with bullet point structure
          return {
            content: `---
title: "${mindmapFile.data.title}"
description: "${mindmapFile.data.description}"
course: "${mindmapFile.data.course}"
chapter: "${mindmapFile.data.chapter || ''}"
---

${mindmapFile.body}`,
            frontmatter: mindmapFile.data
          };
        }
      }

      return null;
    } catch (error) {
      console.error('Error finding mindmap content:', error);
      return null;
    }
  }

  /**
   * Auto-generate mindmap from regular lesson content
   */
  private async generateFromLessonContent(course: string, lessonSlug: string): Promise<MindmapData | null> {
    try {
      const allCourses = await getCollection('courses');
      
      // Find the main lesson file
      const lessonFile = allCourses.find(lesson => {
        const courseName = lesson.data.course?.toLowerCase().replace(/\s+/g, '-');
        const lessonPath = lesson.slug.split('/').slice(1).join('/');
        
        return courseName === course && lessonPath === lessonSlug;
      });

      if (!lessonFile) return null;

      // Extract headings to create a basic mindmap structure
      const generatedContent = this.generateMindmapFromHeadings(
        lessonFile.body, 
        lessonFile.data.title || 'Lesson Content',
        lessonFile.data
      );

      const mindmapData = this.parser.parseContent(generatedContent);
      
      mindmapData.metadata = {
        ...mindmapData.metadata,
        course: lessonFile.data.course || course,
        chapter: lessonFile.data.chapter,
        lessonSlug,
        autoGenerated: true
      };

      return mindmapData;

    } catch (error) {
      console.error('Error auto-generating mindmap:', error);
      return null;
    }
  }

  /**
   * Generate mindmap structure from markdown headings
   */
  private generateMindmapFromHeadings(content: string, title: string, frontmatter: any): string {
    const lines = content.split('\n');
    const headings: Array<{level: number, text: string, content: string[]}> = [];
    let currentContent: string[] = [];

    for (const line of lines) {
      const headingMatch = line.match(/^(#{1,6})\s+(.+)$/);
      
      if (headingMatch) {
        // Save previous heading's content
        if (headings.length > 0) {
          headings[headings.length - 1].content = [...currentContent];
        }
        
        const level = headingMatch[1].length;
        const text = headingMatch[2].replace(/[*_`]/g, '').trim();
        
        headings.push({
          level,
          text,
          content: []
        });
        
        currentContent = [];
      } else if (line.trim() && !line.startsWith('---') && !line.startsWith('import')) {
        // Collect content under current heading
        const cleanLine = line.replace(/[*_`]/g, '').trim();
        if (cleanLine.length > 0 && cleanLine.length < 100) {
          currentContent.push(cleanLine);
        }
      }
    }

    // Save last heading's content
    if (headings.length > 0) {
      headings[headings.length - 1].content = [...currentContent];
    }

    // Build mindmap structure
    let mindmapContent = `---
title: "${title} - Auto-generated Mindmap"
description: "Auto-generated mindmap from lesson content"
course: "${frontmatter.course || 'Unknown Course'}"
chapter: "${frontmatter.chapter || ''}"
---

# ${title}

`;

    // Create hierarchical bullet points
    let currentStack: Array<{level: number, text: string}> = [];

    for (const heading of headings) {
      // Adjust stack based on heading level
      while (currentStack.length > 0 && currentStack[currentStack.length - 1].level >= heading.level) {
        currentStack.pop();
      }

      // Add indentation based on stack depth
      const indent = '  '.repeat(currentStack.length);
      mindmapContent += `${indent}- **${heading.text}**\n`;

      // Add some content points under this heading
      const sampleContent = heading.content.slice(0, 3); // Take first 3 content lines
      for (const contentLine of sampleContent) {
        if (contentLine.length > 10) {
          mindmapContent += `${indent}  - ${contentLine.substring(0, 80)}${contentLine.length > 80 ? '...' : ''}\n`;
        }
      }

      currentStack.push({level: heading.level, text: heading.text});
    }

    return mindmapContent;
  }

  /**
   * Get all available mindmaps for a course
   */
  public async getAvailableMindmaps(course: string): Promise<Array<{slug: string, title: string, description?: string}>> {
    try {
      const allCourses = await getCollection('courses');
      
      const mindmaps = allCourses
        .filter(lesson => {
          const courseName = lesson.data.course?.toLowerCase().replace(/\s+/g, '-');
          const fileName = lesson.slug.split('/').pop() || '';
          
          return courseName === course && (
            fileName.includes('mindmap') || 
            fileName.includes('Mindmap') ||
            fileName === '5_Mindmap'
          );
        })
        .map(lesson => ({
          slug: lesson.slug.split('/').slice(1).join('/'),
          title: lesson.data.title || 'Mindmap',
          description: lesson.data.description
        }));

      return mindmaps;
    } catch (error) {
      console.error('Error getting available mindmaps:', error);
      return [];
    }
  }

  /**
   * Clear content cache
   */
  public clearCache(): void {
    this.contentCache.clear();
  }

  /**
   * Preload mindmaps for a course
   */
  public async preloadCourse(course: string): Promise<void> {
    try {
      const availableMindmaps = await this.getAvailableMindmaps(course);
      
      const loadPromises = availableMindmaps.map(mindmap => 
        this.loadMindmapForLesson(course, mindmap.slug)
      );

      await Promise.all(loadPromises);
      console.log(`Preloaded ${availableMindmaps.length} mindmaps for course: ${course}`);
    } catch (error) {
      console.error(`Failed to preload course ${course}:`, error);
    }
  }
}

// Singleton instance
export const mindmapContentLoader = new MindmapContentLoader();